Adjusted naming in bashrc
Modified function names to more correctly indicate if they are private or public.

diff --git a/dot_bashrc b/dot_bashrc
--- a/dot_bashrc
+++ b/dot_bashrc
@@ -5,9 +5,9 @@
 # If not running interactively, don't do anything
 [[ $- != *i* ]] && return
 
-# All functions and variables are prefixed with ___?BASHRC_ to avoid conflicts
-# with other scripts and for easy cleanup. Assignments that start with three
-# underscores are considered private and should not be used in other scripts.
+# All functions and variables are prefixed with __BASHRC_ or ___BASHRC_ to avoid
+# conflicts with other scripts and for easy cleanup. Assignments that start with
+# three underscores are considered private and should not be used in other scripts.
 
 # Function to print debug output if $__BASHRC_DEBUG is set
 __BASHRC_DEBUG_OUTPUT() {
@@ -17,34 +17,33 @@ __BASHRC_DEBUG_OUTPUT() {
 }
 
 # Function to calculate the ID of a script file
-__BASHRC_ID() {
+___BASHRC_ID() {
     echo "___BASHRC_$(basename "${1%.*}" | tr -d $'\n')" | tr '[:lower:]' '[:upper:]' | tr -c '[:upper:]' '_'
 }
 
 # Function to check if the script is in the correct phase
-__BASHRC_IS_CORRECT_PHASE() {
+___BASHRC_IS_CORRECT_PHASE() {
     local PREFIX="$__BASHRC_PHASE"
     if [ -n "$PREFIX" ]; then
         PREFIX+="-"
     fi
     PREFIX="^$PREFIX."
 
-    [[ "$(basename "$__BASHRC_SCRIPT")" =~ $PREFIX ]]
+    [[ "$(basename "$1")" =~ $PREFIX ]]
 }
 
 # Function to source a modular .bashrc.d script
-__BASHRC_DOT_D_PART_SOURCE() {
-    __BASHRC_DEBUG_OUTPUT "Trying to source '$1'"
-    if ! __BASHRC_IS_CORRECT_PHASE "$1"; then
-        echo "Warning: Skipping sourcing of '$1' as it's not in the correct phase!" 1>&2
+___BASHRC_DOT_D_PART_SOURCE() {
+    if ! ___BASHRC_IS_CORRECT_PHASE "$1"; then
+        echo "Warning: Not sourcing '$1' as it's not in the correct phase!" 1>&2
         return
     fi
 
     # ID contains a unique variable name used as a "guard" to not source the same file twice.
-    local ID="$(__BASHRC_ID "$1")"
+    local ID="$(___BASHRC_ID "$1")"
     # Indirect lookup of the variable name inside ID
     if [ -z "${!ID}" ]; then
-        # We set it as "sourced" right away to avoid an infinite look in case of __BASHRC_DOT_D_PART_SOURCE "source"-cycles where two files are marked as needing each other
+        # Set it as "sourced" right away to avoid an infinite loop in case of ___BASHRC_DOT_D_PART_SOURCE "source"-cycles where two files are marked as needing each other
         eval "$ID=sourced"
 
         __BASHRC_DEBUG_OUTPUT "Sourcing '$1'"
@@ -74,17 +73,15 @@ __BASHRC_PHASE_PARALLEL_SOURCE_ADD() {
 ___BASHRC_PHASE_PARALLEL_SOURCE_APPLY() {
     __BASHRC_DOT_D_VERSION="$(awk '{timesum+=$1} END {print timesum}' <(stat -c %Y "$HOME/.bashrc.d/"*))"
 
-    __BASHRC_BOOT_ID="$(cat /proc/sys/kernel/random/boot_id)"
-
-    __BASHRC_CACHE_FILE="/tmp/.bashrc_cache_${USER}_${__BASHRC_PHASE:-main}_${__BASHRC_DOT_D_VERSION}_${__BASHRC_BOOT_ID}"
-    if [ -e "$__BASHRC_CACHE_FILE" ]; then
-        __BASHRC_DEBUG_OUTPUT "Sourcing detected cache file '$__BASHRC_CACHE_FILE' for increased performance"
-        source "$__BASHRC_CACHE_FILE"
+    ___BASHRC_CACHE_FILE="/tmp/.bashrc_cache_${USER}_${__BASHRC_PHASE:-main}_${__BASHRC_DOT_D_VERSION}"
+    if [ -e "$___BASHRC_CACHE_FILE" ]; then
+        __BASHRC_DEBUG_OUTPUT "Sourcing detected cache file '$___BASHRC_CACHE_FILE' for increased performance"
+        source "$___BASHRC_CACHE_FILE"
         return
     fi
 
     __BASHRC_DEBUG_OUTPUT "Applying parallel source scripts to the current shell $___BASHRC_PHASE_PARALLEL_SOURCE_CONTENT"
-    eval "$___BASHRC_PHASE_PARALLEL_SOURCE_CONTENT" >"$__BASHRC_CACHE_FILE"
+    eval "$___BASHRC_PHASE_PARALLEL_SOURCE_CONTENT" >"$___BASHRC_CACHE_FILE"
     __BASHRC_DEBUG_OUTPUT "Done applying parallel source scripts"
 }
 
@@ -94,14 +91,14 @@ for __BASHRC_PHASE in pre '' post; do
     ___BASHRC_PHASE_PARALLEL_SOURCE_INIT
     for __BASHRC_SCRIPT in "$HOME/.bashrc.d/"*; do
         # Skip non-matching phases
-        __BASHRC_IS_CORRECT_PHASE "$__BASHRC_SCRIPT" || continue
+        ___BASHRC_IS_CORRECT_PHASE "$__BASHRC_SCRIPT" || continue
 
         if [ ! -f "${__BASHRC_SCRIPT}" ]; then
             echo "Warning: Skipping '$__BASHRC_SCRIPT' as it's not a regular file!" 1>&2
             continue
         fi
 
-        __BASHRC_DOT_D_PART_SOURCE "${__BASHRC_SCRIPT}"
+        ___BASHRC_DOT_D_PART_SOURCE "${__BASHRC_SCRIPT}"
     done
     ___BASHRC_PHASE_PARALLEL_SOURCE_APPLY
 done
